language: node_js
node_js:
  - '12'
before_deploy: npm run build
deploy:
  provider: npm
  email: tjj.rikap@gmail.com
  skip_cleanup: true
  api_key: $NPM_TOKEN
  on:
    tags: true
    branch: master
  tag: latest