name: Test and Build

on:
  push:
    branches: [ '**' ]
    tags-ignore: [ 'v1.*', 'v2.*' ]
  pull_request:
  workflow_call:
    inputs:
      upload_artifact:
        required: false
        type: boolean

jobs:
  test_and_build:
    name: Test and Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 16.x ]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm test
    - run: npm run build
    - uses: actions/upload-artifact@master
      if: inputs.upload_artifact && matrix.node-version == '16.x'
      with:
        name: bld
        path: "./bld"
